all: example_phoneCalls

example_phoneCalls: example_phoneCalls.c
	gcc -Wall -O3 example_phoneCalls.c -o example_phoneCalls
#	gcc -Wall -g -fprofile-arcs -ftest-coverage example_phoneCalls.c -o example_phoneCalls



clean:
	-rm example_phoneCalls example_phoneCalls.gcno example_phoneCalls.gcda example_phoneCalls.c.gcov

